networks:
  internal:
    driver: overlay
    attachable: true

volumes:
  mongo_auth:
  mongo_reviews:
  postgres_games:
  rabbitmq_data:

services:

  # ---------------- API GATEWAY ----------------
  api-gateway:
    image: api-gateway:latest
    build: ./api-gateway
    ports:
      - "8080:8080"
    networks:
      - internal
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  # ---------------- AUTH SERVICE ----------------
  auth-service:
    image: auth-service:latest
    networks:
      - internal
    ports:
      - "4001:4001"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      - MONGO_URI=mongodb://mongo-auth:27017/auth
      - JWT_SECRET=supersecret

  mongo-auth:
    image: mongo:6
    volumes:
      - mongo_auth:/data/db
    networks:
      - internal
    deploy:
      replicas: 1

  mongo-express:
    image: mongo-express:1.0.2
    networks:
      - internal
    ports:
      - "8082:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo-auth
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH=false
    deploy:
      replicas: 1

  # ---------------- GAME SERVICE ----------------
  game-service:
    image: game-service:latest
    networks:
      - internal
    ports:
      - "4002:4002"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres-games:5432/games
      - AUTH_SERVICE_URL=http://auth-service:4001/verify

  postgres-games:
    image: postgres:15
    environment:
      POSTGRES_DB: games
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_games:/var/lib/postgresql/data
    networks:
      - internal

  # ---------------- REVIEW SERVICE ----------------
  review-service:
    image: review-service:latest
    build: ./review-service
    networks:
      - internal
    ports:
      - "4003:4003"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    environment:
      - MONGO_URI=mongodb://mongo-reviews:27017/reviews
      - AUTH_SERVICE_URL=http://auth-service:4001/verify
      - RABBITMQ_URL=amqp://rabbitmq

  mongo-reviews:
    image: mongo:6
    volumes:
      - mongo_reviews:/data/db
    networks:
      - internal

  # ---------------- ANALYTICS SERVICE ----------------
  analytics-service:
    image: analytics-service:latest
    build: ./analytics-service
    networks:
      - internal
    deploy:
      replicas: 1
    environment:
      - GAME_SERVICE_URL=http://game-service:4002
      - REVIEW_SERVICE_URL=http://review-service:4003/reviews

  # ---------------- NOTIFICATION SERVICE ----------------
  notification-service:
    image: notification-service:latest
    build: ./notification-service
    networks:
      - internal
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      - RABBITMQ_URL=amqp://rabbitmq

  # ---------------- RABBITMQ ----------------
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - internal
    deploy:
      replicas: 1
